#!/bin/sh
# Copyright (C) 2012  Glen Pitt-Pladdy
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
# See: https://www.pitt-pladdy.com/blog/_20140826-094101_0100_NTP_Monitoring_on_Cacti_over_SNMP/
#
# Version 20140826
#


# ms => s (/1000)
toseconds() {
	while read in; do
		echo "scale=6; $in / 1000" | bc
	done
}

# on Linux this gives all times in seconds (base unit)
# 9 = offset
# 10 = jitter
times=`ntpq -np | tail -n +3 | awk '{print $'$1'}' | toseconds`
# 7 = offset
# 8 = dispersion
#times=`ntpdc -np | tail -n +3 | awk '{print $'$1'}'`
# for absolute offest: | sed s/^-//
# for dispersion use $8
echo "$times" | sort -n | head -n 1
echo "$times" | sort -rn | head -n 1
echo "$times"

